name: 'Main'

on: [workflow_dispatch, push, pull_request]

jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out Git repository'
        uses: 'actions/checkout@v4'

      - name: 'Use Node.js 22'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 22
          cache: 'npm'

      - name: Cache node modules
        id: cache-npm
        uses: 'actions/cache@v4'
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Lint'
        run: 'npm run lint'

  test:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out Git repository'
        uses: 'actions/checkout@v4'

      - name: 'Use Node.js 22'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 22
          cache: 'npm'

      - name: Cache node modules
        id: cache-npm
        uses: 'actions/cache@v4'
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Test'
        run: 'npm run test:ci'

  build:
    name: 'Build'
    needs: ['lint', 'test']
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out Git repository'
        uses: 'actions/checkout@v4'

      - name: 'Use Node.js 22'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 22
          cache: 'npm'

      - name: Cache node modules
        id: cache-npm
        uses: 'actions/cache@v4'
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - name: 'Install dependencies'
        run: 'npm ci'

      - name: 'Build'
        run: 'npm run build'
